<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Auturge.Quantity</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Auturge.Identifiers\Auturge.Identifiers.csproj"/>
        <InternalsVisibleTo Include="Auturge.Quantity.Tests"/>
        <InternalsVisibleTo Include="Auturge.Quantity.Numerics"/>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="RS.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>RS.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="RS.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>RS.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
